version: "3.8"

services:
  redis:
    image: redis:7
    container_name: multiagent_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./chroma_store:/app/chroma_store
      - ./backend/uploads:/app/uploads
    environment:
      - DATABASE_URL=sqlite:///./backend.db
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - redis
